[[pages]]
path = "app.py"
name = "Start"

[[pages]]
path = "tradingplatformpoc/app/pages/setup_configuration.py"
name = "Setup configuration"

[[pages]]
path = "tradingplatformpoc/app/pages/run_simulation.py"
name = "Run simulation"

[[pages]]
path = "tradingplatformpoc/app/pages/general_results.py"
name = "General results"

[[pages]]
path = "tradingplatformpoc/app/pages/results_by_agent.py"
name = "Results by agent"

[[pages]]
path = "tradingplatformpoc/app/pages/scenario_comparison.py"
name = "Scenario comparison"