[[pages]]
path = "app.py"
name = "Start"

[[pages]]
path = "tradingplatformpoc/app/pages/setup_simulation.py"
name = "Setup simulation"

[[pages]]
path = "tradingplatformpoc/app/pages/run_simulation.py"
name = "Run simulation"

[[pages]]
path = "tradingplatformpoc/app/pages/view_results.py"
name = "View results"

[[pages]]
name = ""
icon = ""
is_section = true

[[pages]]
path = "tradingplatformpoc/app/pages/general_results.py"
name = "General results"

[[pages]]
path = "tradingplatformpoc/app/pages/results_by_agent.py"
name = "Results by agent"